######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 23 12:12:34 2010
######################################################################

TEMPLATE = lib
CONFIG  += dll
TARGET = rssparser
DEPENDPATH += .
INCLUDEPATH += .
QT      += core xmlpatterns
HEADERS += rssparser.h
SOURCES += rssparser.cpp

# In linux ensure the specified path has write permission
# sudo chmod 777 /usr/lib
# sudo chmod 777 /usr/include
win32:{DESTDIR = c:/decii/lib
headers.path = c:/decii/include/rsssuite}
unix:{DESTDIR = /usr/lib
headers.path = /usr/include/rsssuite}
headers.files = rssparser.h
INSTALLS += headers
PRE_TARGETDEPS += install_headers
# copying dependent files in unix has a different approach
# build_pass is not working
# refer http://paulf.free.fr/undocumented_qmake.html
# use  build_pass:ALL_DEPS += install_headers in win32 in case of issues
